### ISSUE TITLE
Invalid gulp.targets entry causes failure to load project

### ISSUE THREAD

**Issue by Sschlenker** [CUModSquad/cu-boilerplate-component#2]
This line calls out to an invalid location which causes the project to fail on loading.

Line 42 (cu-boilerplate-component.csproj)
    
    <Import Project="$(MSBuildProjectDirectory)\msbuild\gulp.targets"/>

**Comment by saddieeiddas** [comment]
Has now been fixed here https://github.com/CUModSquad/cu-build-tools/pull/13 should now build `csproj` without this import when `vsgen` task is run.

I will run `vsgen` and update the existing `csproj` here so things can open up without running anything.
